name = "junk-atelier-gallery"
main = "src/index.ts"
compatibility_date = "2026-06-01"

[vars]
ALLOWED_ORIGIN = "https://xavpain.github.io"

[[d1_databases]]
binding = "DB"
database_name = "junk-gallery"
database_id = "36c96d96-7043-4b87-ad7f-f47d3793d55c"
